import type {Metadata} from "next";
import {Baskervville, Inter} from "next/font/google";
import "./globals.css";
import Banner from "@/components/topBanner/banner";
import Header from "@/components/header/header";
import HeaderMenu from "@/components/headerMenu/headerMenu";
import Footer from "@/components/footer/footer";
import PopOutMenu from "@/components/hambugerMenu/popOutMenu";
import PopOutMenuProvider from "@/contexts/popOutMenuContext";

const inter = Inter({subsets: ["latin"]});
const baskerVille = Baskervville({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Newspark",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <PopOutMenuProvider>
            <html lang="en">
            <body className={inter.className + " flex flex-col justify-start items-center"}>
            <PopOutMenu/>
            <Banner/>
            <hr className="border-dashed w-full hidden md:block"/>
            <Header font={baskerVille}/>
            <HeaderMenu/>
            {children}
            <div className="lg:my-5"></div>
            <Footer/>
            </body>
            </html>
        </PopOutMenuProvider>
    );
}
